default_language_version:
  python: python3

repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-symlinks
        exclude: ^auth/auth/node_modules
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
        exclude: >
          (?x)(
            ^service-template/
          )
      - id: debug-statements
        exclude: >
          (?x)(
            ^infrastructure/
            | ^service-template/
          )
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
      - id: check-yaml
        name: Check Yaml --unsafe # for files with undefined constructors (e.g. AWS provides them)
        args:
          - --allow-multiple-documents
          - --unsafe
        files: >
          (?x)(
            ^cms/app/cf/prod-cf.yaml$
          )
      - id: detect-private-key

  - repo: git://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
        args:
          - -x
        files: \.(sh|bashrc)$
        exclude: >
          (?x)(
            ^service-template/
          )

  - repo: git://github.com/pre-commit/mirrors-pylint
    rev: v2.6.0
    hooks:
      - id: pylint
        args:
          - --reports=no
        files: \/.*\.py$
        exclude: >
          (?x)(
            ^service-template/
          )

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        exclude: >
          (?x)(
              ^service-template/
          )

  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort
        types: [file, python]
        args:
          - --settings-path=tox.ini
